
@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml
!include FONTAWESOME/shopify.puml
!include FONTAWESOME/google_drive.puml
!include FONTAWESOME/truck.puml

LAYOUT_WITH_LEGEND()

' ---

Person_Ext(user1, "お客様\n（購入者）", "Storesで商品を注文")
Person_Ext(user2, "お客様\n（お届け先）", "商品を受け取る\n（≒購入者）")

Boundary(c1, "利用しているシステム") {
    System_Ext(stores, "STORES", "商品展示\n注文管理", "shopify")
    System(gas, "出荷作業支援", "手作業を減らすため\n作業の一部を自動化", "google_drive")
    System_Ext(yamato, "ヤマト運輸", "伝票発行および\n集荷・配送", "truck")
}

Person(staff, "ショップスタッフ", "送り状作成\n出荷梱包作業")

' ---

Rel(user1,  stores, "商品の注文")
Rel(user1,  user2,  "（贈答）")
Rel(stores, staff,  "CSV")
Rel(staff,  gas,    "CSV")
Rel(gas,    staff,  "コピペ")
Rel(yamato, staff,  "送り状発行")
Rel(staff,  yamato, "配送依頼")
Rel(yamato, user2,  "お届け")

@enduml


Person_Ext(customer, "Customer", "A customer wanting to buy a horrendous hat")

System(site, "eComm System", "Displays hats for sale, takes orders and payments")
System(fulfil, "Fulfilment System", "Fulfilment system that tracks inventory and ships orders to customers")

System_Ext(payments, "Payment Gateway", "Provides payment service") 

Rel(customer, site, "Orders hat\nusing")
Rel(site, payments, "Redirects\npayment to")
Rel(site, fulfil, "Sends\norder to")
Rel(fulfil, site, "Lists hats\nfor sale")
Rel(fulfil, customer, "Ships\nhat to")
Rel(fulfil, customer, "Emails\ninvoice to")
