@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

' オーダー情報
SetPropertyHeader("No.", "プロパティ")
AddProperty("01", "オーダー番号")
AddProperty("02", "ステータス")
AddProperty("03", "支払方法")
AddProperty("04", "オーダー日")
AddProperty("05", "決済完了日")
AddProperty("06", "発送開始時期")
AddProperty("07", "発送終了時期")
AddProperty("08", "発送完了日")
AddProperty("09", "アイテム名")
AddProperty("10", "種類")
AddProperty("11", "品番")
AddProperty("12", "バーコード")
AddProperty("13", "個数")
AddProperty("14", "小計")
AddProperty("15", "配送料")
AddProperty("16", "販売タイプ")
AddProperty("17", "販売サイクル")
AddProperty("18", "クーポン名")
AddProperty("19", "クーポン割引額")
AddProperty("20", "ディスカウント割引額")
AddProperty("21", "ディスカウント率")
AddProperty("22", "まとめて割")
AddProperty("23", "セット割")
AddProperty("24", "代引き手数料")
AddProperty("25", "オプション手数料")
AddProperty("26", "合計")
AddProperty("27", "内消費税")
AddProperty("28", "合計(10%)")
AddProperty("29", "内消費税(10%)")
AddProperty("30", "合計(8%)")
AddProperty("31", "内消費税(8%)")
AddProperty("32", "決済手数料")
AddProperty("33", "決済手数料率")
AddProperty("34", "氏(配送先)")
AddProperty("35", "名(配送先)")
AddProperty("36", "郵便番号(配送先)")
AddProperty("37", "都道府県(配送先)")
AddProperty("38", "住所(配送先)")
AddProperty("39", "電話番号(配送先)")
AddProperty("40", "氏(購入者)")
AddProperty("41", "名(購入者)")
AddProperty("42", "郵便番号(購入者)")
AddProperty("43", "都道府県(購入者)")
AddProperty("44", "住所(購入者)")
AddProperty("45", "電話番号(購入者)")
AddProperty("46", "メールアドレス")
AddProperty("47", "領収書宛名")
AddProperty("48", "備考")
AddProperty("49", "メモ")
ContainerDb(order1, "オーダー情報CSV", "STORESからダウンロード")

' チェックシート
SetPropertyHeader("No.", "プロパティ", "備考")
AddProperty("01", "オーダー番号","複数レコードある場合、2行目以降を空白に変える")
AddProperty("09", "アイテム名","")
AddProperty("13", "個数","")
AddProperty("14", "小計","")
AddProperty("26", "合計","")
AddProperty("34", "氏(配送先)","")
AddProperty("35", "名(配送先)","")
AddProperty("36", "郵便番号(配送先)","")
AddProperty("37", "都道府県(配送先)","")
AddProperty("38", "住所(配送先)","")
AddProperty("39", "電話番号(配送先)","")
AddProperty("47", "領収書宛名","")
AddProperty("48", "備考","")
AddProperty("40", "氏(購入者)","配送先≠購入者の場合のみ表示")
AddProperty("41", "名(購入者)","配送先≠購入者の場合のみ表示")
AddProperty("42", "郵便番号(購入者)","配送先≠購入者の場合のみ表示")
AddProperty("43", "都道府県(購入者)","配送先≠購入者の場合のみ表示")
AddProperty("44", "住所(購入者)","配送先≠購入者の場合のみ表示")
AddProperty("45", "電話番号(購入者)","配送先≠購入者の場合のみ表示")
AddProperty("49", "メモ","")
ContainerDb(order2, "オーダー情報チェックシート", "Google SpreadSheetに生成")

' ---

Rel_R(order1, order2, "抽出", "GAS")

' ---

' LAYOUT_TOP_DOWN() or LAYOUT_LEFT_RIGHT()
SHOW_DYNAMIC_LEGEND()

@enduml

