@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddTagSupport("humanwork", $borderColor="#F58B00", $fontColor="#F58B00")

!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!define MATERIAL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/material

!include FONTAWESOME/users.puml
!include FONTAWESOME/shopify.puml
!include FONTAWESOME/truck.puml
!include MATERIAL/laptop_mac.puml

' ---

Person_Ext(user1, "お客様\n（購入者）", "STORESで商品を注文")
System_Ext(stores, "STORES", "商品の販売および\n注文・出荷の管理", "shopify")
Boundary(b1, "ショップ") {
    Person(staff, "ショップスタッフ", "送り状作成\n出荷梱包作業")
    System(pc, "パソコン作業\n※意外に手作業発生※", "CSVデータ加工\n追加情報入力", "laptop_mac", $tags="humanwork")
}
System_Ext(yamato, "ヤマト運輸", "伝票発行および\n集荷・配送", "truck")

' ---

Rel_R(user1,  stores, "注文")
Rel_D(stores, staff,  "CSV")
Rel_L(staff,  pc,     "各種作業")
Rel_R(staff,  yamato, "配送依頼")

' ---

SHOW_DYNAMIC_LEGEND()

@enduml
