'' 
'' コンポーネント図のうち、送り状パートを表現するもの
'' 

@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

' オーダー情報
!includesub ./orderCsv.puml!ORDERCSV

' ヤマトB2システム送り状
SetPropertyHeader("No.", "プロパティ", "STORES オーダー情報との関係", "自動化での対応事項")
AddProperty("00", "お客様管理番号", "00 オーダー番号", " ")
AddProperty("01", "送り状種類", "空欄", " ")
AddProperty("02", "クール区分", "空欄", " ")
AddProperty("03", "伝票番号", "空欄", " ")
AddProperty("04", "出荷予定日", "固定値", " ")
AddProperty("05", "お届け予定日", "空欄", " ")
AddProperty("06", "配達時間帯", "空欄", " ")
AddProperty("07", "お届け先コード", "空欄", " ")
AddProperty("08", "お届け先電話番号", "空欄", " ")
AddProperty("09", "お届け先電話番号枝番", "空欄", " ")
AddProperty("10", "お届け先郵便番号", "35 郵便番号(配送先)", " ")
AddProperty("11", "お届け先住所", "36 都道府県(配送先) + 37 住所(配送先)", " ")
AddProperty("12", "お届け先アパートマンション名", "37 住所(配送先)の一部", " ")
AddProperty("13", "お届け先会社・部門１", "空欄", " ")
AddProperty("14", "お届け先会社・部門２", "空欄", " ")
AddProperty("15", "お届け先名", "33 氏(配送先) + [ ] + 34 名(配送先) ", " ")
AddProperty("16", "お届け先名(ｶﾅ)", "空欄", " ")
AddProperty("17", "敬称", "空欄", "固定値（様）埋め")
AddProperty("18", "ご依頼主コード", "空欄", " ")
AddProperty("19", "ご依頼主電話番号", "固定値(ショップ)", "配送先≠購入者ならば、購入者に置換")
AddProperty("20", "ご依頼主電話番号枝番", "固定値(ショップ)", "配送先≠購入者ならば、購入者に置換")
AddProperty("21", "ご依頼主郵便番号", "固定値(ショップ)", "配送先≠購入者ならば、購入者に置換")
AddProperty("22", "ご依頼主住所", "固定値(ショップ)", "表記置換、配送先≠購入者ならば、購入者に置換")
AddProperty("23", "ご依頼主アパートマンション", "空欄", " ")
AddProperty("24", "ご依頼主名", "固定値(ショップ)", "配送先≠購入者ならば、購入者に置換（氏と名を連結）")
AddProperty("25", "ご依頼主名(ｶﾅ)", "空欄", "固定値埋め")
AddProperty("26", "品名コード１", "空欄", " ")
AddProperty("27", "品名１", "複数レコードは[, ]で連結", " ")
AddProperty("28", "品名コード２", "空欄", " ")
AddProperty("29", "品名２", "空欄", " ")
AddProperty("30", "荷扱い１", "空欄", "固定値埋め")
AddProperty("31", "荷扱い２", "空欄", "固定値埋め")
AddProperty("32", "記事", "空欄", " ")
AddProperty("33", "ｺﾚｸﾄ代金引換額（税込)", "空欄", " ")
AddProperty("34", "内消費税額等", "空欄", " ")
AddProperty("35", "止置き", "空欄", " ")
AddProperty("36", "営業所コード", "空欄", " ")
AddProperty("37", "発行枚数", "空欄", " ")
AddProperty("38", "個数口表示フラグ", "空欄", " ")
AddProperty("39", "請求先顧客コード", "固定値", " ")
AddProperty("40", "請求先分類コード", "空欄", " ")
AddProperty("41", "運賃管理番号", "固定値", "固定値埋め")
AddProperty("42", "クロネコwebコレクトデータ登録", "空欄", "以下未使用")
AddProperty("43", "クロネコwebコレクト加盟店番号", "空欄", " ")
AddProperty("44", "クロネコwebコレクト申込受付番号１", "空欄", " ")
AddProperty("45", "クロネコwebコレクト申込受付番号２", "空欄", " ")
AddProperty("46", "クロネコwebコレクト申込受付番号３", "空欄", " ")
AddProperty("47", "お届け予定ｅメール利用区分", "空欄", " ")
AddProperty("48", "お届け予定ｅメールe-mailアドレス", "45 メールアドレス", " ")
AddProperty("49", "入力機種","以下No.94まで未使用", " ")
AddProperty("...", "...", "...", " ")
AddProperty("95", "備考欄", "以下オーダー情報転記", "")
AddProperty("96", "メモ", " ", " ")
AddProperty("97", "決済方法", " ", " ")
AddProperty("98", "ステータス", " ", " ")
ContainerDb(yamato, "ヤマト送り状作成支援用データ／送り状CSVを加工", "Google SpreadSheetにシートを生成")

' ---

Rel_R(order1, yamato, "01ステータス「未入金」レコードを抽出して挿入", "GAS")

' ---

' LAYOUT_TOP_DOWN() or LAYOUT_LEFT_RIGHT()
SHOW_DYNAMIC_LEGEND()

@enduml

' ヤマトB2システム送り状
SetPropertyHeader("No.", "プロパティ", "備考")
AddProperty("00", "お客様管理番号"," ")
AddProperty("01", "送り状種類"," ")
AddProperty("02", "クール区分"," ")
AddProperty("03", "伝票番号"," ")
AddProperty("04", "出荷予定日"," ")
AddProperty("05", "お届け予定日"," ")
AddProperty("06", "配達時間帯"," ")
AddProperty("07", "お届け先コード"," ")
AddProperty("08", "お届け先電話番号"," ")
AddProperty("09", "お届け先電話番号枝番"," ")
AddProperty("10", "お届け先郵便番号"," ")
AddProperty("11", "お届け先住所"," ")
AddProperty("12", "お届け先アパートマンション名"," ")
AddProperty("13", "お届け先会社・部門１"," ")
AddProperty("14", "お届け先会社・部門２"," ")
AddProperty("15", "お届け先名"," ")
AddProperty("16", "お届け先名(ｶﾅ)"," ")
AddProperty("17", "敬称"," ")
AddProperty("18", "ご依頼主コード"," ")
AddProperty("19", "ご依頼主電話番号"," ")
AddProperty("20", "ご依頼主電話番号枝番"," ")
AddProperty("21", "ご依頼主郵便番号"," ")
AddProperty("22", "ご依頼主住所"," ")
AddProperty("23", "ご依頼主アパートマンション"," ")
AddProperty("24", "ご依頼主名"," ")
AddProperty("25", "ご依頼主名(ｶﾅ)"," ")
AddProperty("26", "品名コード１"," ")
AddProperty("27", "品名１"," ")
AddProperty("28", "品名コード２"," ")
AddProperty("29", "品名２"," ")
AddProperty("30", "荷扱い１"," ")
AddProperty("31", "荷扱い２"," ")
AddProperty("32", "記事"," ")
AddProperty("33", "ｺﾚｸﾄ代金引換額（税込)"," ")
AddProperty("34", "内消費税額等"," ")
AddProperty("35", "止置き"," ")
AddProperty("36", "営業所コード"," ")
AddProperty("37", "発行枚数"," ")
AddProperty("38", "個数口表示フラグ"," ")
AddProperty("39", "請求先顧客コード"," ")
AddProperty("40", "請求先分類コード"," ")
AddProperty("41", "運賃管理番号"," ")
AddProperty("42", "クロネコwebコレクトデータ登録"," ")
AddProperty("43", "クロネコwebコレクト加盟店番号"," ")
AddProperty("44", "クロネコwebコレクト申込受付番号１"," ")
AddProperty("45", "クロネコwebコレクト申込受付番号２"," ")
AddProperty("46", "クロネコwebコレクト申込受付番号３"," ")
AddProperty("47", "お届け予定ｅメール利用区分"," ")
AddProperty("48", "お届け予定ｅメールe-mailアドレス"," ")
AddProperty("49", "入力機種"," ")
AddProperty("50", "お届け予定ｅメールメッセージ"," ")
AddProperty("51", "お届け完了ｅメール利用区分"," ")
AddProperty("52", "お届け完了ｅメールe-mailアドレス"," ")
AddProperty("53", "お届け完了ｅメールメッセージ"," ")
AddProperty("54", "クロネコ収納代行利用区分"," ")
AddProperty("55", "予備"," ")
AddProperty("56", "収納代行請求金額(税込)"," ")
AddProperty("57", "収納代行内消費税額等"," ")
AddProperty("58", "収納代行請求先郵便番号"," ")
AddProperty("59", "収納代行請求先住所"," ")
AddProperty("60", "収納代行請求先住所（アパートマンション名）"," ")
AddProperty("61", "収納代行請求先会社・部門名１"," ")
AddProperty("62", "収納代行請求先会社・部門名２"," ")
AddProperty("63", "収納代行請求先名(漢字)"," ")
AddProperty("64", "収納代行請求先名(カナ)"," ")
AddProperty("65", "収納代行問合せ先名(漢字)"," ")
AddProperty("66", "収納代行問合せ先郵便番号"," ")
AddProperty("67", "収納代行問合せ先住所"," ")
AddProperty("68", "収納代行問合せ先住所（アパートマンション名）"," ")
AddProperty("69", "収納代行問合せ先電話番号"," ")
AddProperty("70", "収納代行管理番号"," ")
AddProperty("71", "収納代行品名"," ")
AddProperty("72", "収納代行備考"," ")
AddProperty("73", "複数口くくりキー"," ")
AddProperty("74", "検索キータイトル1"," ")
AddProperty("75", "検索キー1"," ")
AddProperty("76", "検索キータイトル2"," ")
AddProperty("77", "検索キー2"," ")
AddProperty("78", "検索キータイトル3"," ")
AddProperty("79", "検索キー3"," ")
AddProperty("80", "検索キータイトル4"," ")
AddProperty("81", "検索キー4"," ")
AddProperty("82", "検索キータイトル5"," ")
AddProperty("83", "検索キー5"," ")
AddProperty("84", "予備"," ")
AddProperty("85", ";"," ")
AddProperty("86", "投函予定メール利用区分"," ")
AddProperty("87", "投函予定メールe-mailアドレス"," ")
AddProperty("88", "投函予定メールメッセージ"," ")
AddProperty("89", "投函完了メール（お届け先宛）利用区分"," ")
AddProperty("90", "投函完了メール（お届け先宛）e-mailアドレス"," ")
AddProperty("91", "投函完了メール（お届け先宛）メールメッセージ"," ")
AddProperty("92", "投函完了メール（ご依頼主宛）利用区分"," ")
AddProperty("93", "投函完了メール（ご依頼主宛）e-mailアドレス"," ")
AddProperty("94", "投函完了メール（ご依頼主宛）メールメッセージ"," ")
AddProperty("95", "備考欄"," ")
AddProperty("96", "メモ"," ")
AddProperty("97", "決済方法"," ")
AddProperty("98", "ステータス"," ")
ContainerDb(yamato, "送り状CSV", "GASの配列上に存在")
