
@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!define MATERIAL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/material

!include FONTAWESOME/shopify.puml
!include FONTAWESOME/file_excel.puml
!include FONTAWESOME/google_drive.puml
!include FONTAWESOME/cloud.puml
!include FONTAWESOME/print.puml
!include FONTAWESOME/truck.puml

LAYOUT_WITH_LEGEND()

' ---

Boundary(b1, "STORES") {
    System_Ext(stores1, "ショップページ", "オーダーCSV出力\n送り状CSV出力", "cloud")
}
Boundary(b2, "GAS (Google Apps Script)") {
    System(gas1, "ヤマト伝票作成支援", "送り状CSVを加工", "google_drive")
    System(gas2, "チェックシート作成", "オーダーCSVを加工", "google_drive")
}
Boundary(b4, "ショップ") {
    Person(staff,   "スタッフ", "パソコンで各種作業")
    Container(excel,   "エクセル", "MS Excel", "送り状データ編集", "file_excel")
    Container(printer, "プリンタ", "インクジェット", "送り状印刷", "print")
}
Boundary(b3, "ヤマト運輸") {
    System_Ext(yamato1, "送り状発行システム\nB2クラウド", " ", "cloud")
    System_Ext(yamato2, "集荷・配送", "荷姿1\n荷姿2 ", "truck")
}

' ---

Rel(stores1, staff, "CSV")
Rel(staff, gas1, "CSV")
Rel(staff, gas2, "CSV")
Rel_R(staff, excel, "編集")
Rel(gas1, excel, "コピペ")
Rel(gas2, staff, "印刷")
Rel(excel, yamato1, "Excel")
Rel(yamato1, printer, "印刷")
Rel(printer, yamato2, "配送依頼")

@enduml



' ' ______

' Rel(stores2, staff, "CSV")

' Boundary(b1, "STORES") {
' '    System_Ext(orderdb, "オーダー情報", " ", "database")
'     System_Ext(stores1, "STORES管理者ページ", "オーダー情報\nヤマトB2伝票", "file_csv")
' '    System_Ext(stores2, "STORES管理者ページ", "ヤマトB2伝票用CSV発行", "file_csv")
' }
' Boundary(b2, "GAS (Google App Script)") {
'     System(gas1, "ヤマト伝票作成支援", "項目の自動入力", "google_drive")
'     System(gas2, "チェックシート作成", "オーダー情報を加工", "google_drive")
' }
' Boundary(b4, "ショップ") {
' '    System(staff, "スタッフのパソコン", "各種作業の実施", "laptop_mac")
'     Person(staff, "ショップスタッフ", "パソコンで各種作業")
'     System(excel, "エクセルシート", "出荷伝票の編集", "file_excel")
' }
' Boundary(b3, "ヤマト運輸") {
'     System_Ext(yamato1, "B2伝票発行システム", " ", "print")
'     System_Ext(yamato2, "集荷・配送", " ", "truck")
' }


' ' ---

' ' Rel(orderdb, stores1, "データ抽出")
' ' Rel(orderdb, stores2, "データ変換")
' Rel(stores1, staff, "CSV")
' ' Rel(stores2, staff, "CSV")
' Rel(staff, gas1, "CSV")
' Rel(staff, gas2, "CSV")
' Rel_L(staff, excel, "編集")
' Rel(gas1, excel, "コピペ")
' Rel(gas2, staff, "印刷")
' Rel(excel, yamato1, "Excel")
' Rel(yamato1, staff, "印刷")
' Rel(staff, yamato2, "配送依頼")
