@startuml
' parts for include

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

!startsub ORDERCSV

SetPropertyHeader("No.", "プロパティ")
AddProperty("00", "オーダー番号")
AddProperty("01", "ステータス")
AddProperty("02", "支払方法")
AddProperty("03", "オーダー日")
AddProperty("04", "決済完了日")
AddProperty("05", "発送開始時期")
AddProperty("06", "発送終了時期")
AddProperty("07", "発送完了日")
AddProperty("08", "アイテム名")
AddProperty("09", "種類")
AddProperty("10", "品番")
AddProperty("11", "バーコード")
AddProperty("12", "個数")
AddProperty("13", "小計")
AddProperty("14", "配送料")
AddProperty("15", "販売タイプ")
AddProperty("16", "販売サイクル")
AddProperty("17", "クーポン名")
AddProperty("18", "クーポン割引額")
AddProperty("19", "ディスカウント割引額")
AddProperty("20", "ディスカウント率")
AddProperty("21", "まとめて割")
AddProperty("22", "セット割")
AddProperty("23", "代引き手数料")
AddProperty("24", "オプション手数料")
AddProperty("25", "合計")
AddProperty("26", "内消費税")
AddProperty("27", "合計(10%)")
AddProperty("28", "内消費税(10%)")
AddProperty("29", "合計(8%)")
AddProperty("30", "内消費税(8%)")
AddProperty("31", "決済手数料")
AddProperty("32", "決済手数料率")
AddProperty("33", "氏(配送先)")
AddProperty("34", "名(配送先)")
AddProperty("35", "郵便番号(配送先)")
AddProperty("36", "都道府県(配送先)")
AddProperty("37", "住所(配送先)")
AddProperty("38", "電話番号(配送先)")
AddProperty("39", "氏(購入者)")
AddProperty("40", "名(購入者)")
AddProperty("41", "郵便番号(購入者)")
AddProperty("42", "都道府県(購入者)")
AddProperty("43", "住所(購入者)")
AddProperty("44", "電話番号(購入者)")
AddProperty("45", "メールアドレス")
AddProperty("46", "領収書宛名")
AddProperty("47", "備考")
AddProperty("48", "メモ")
ContainerDb(order1, "オーダー情報CSV", "STORESからダウンロード")
!endsub

@enduml
